title: "Laurie - Services à domicile"
description: "Services à domicile à Cholet"

url: "https://laurie-services.github.io"
baseurl: ""

lang: "fr"
timezone: "Europe/Paris"

markdown: kramdown
permalink: /:basename.html

plugins: []

# Flag utilisé pour afficher un message de pré-lancement dans le layout
prelaunch: true

# Enregistrement SAP validé
sap_validated: false

# Médiateur de la consommation désigné
mediator_enabled: false

# L'avance immédiate est active
avance_immediate_active: false

